// components/sidebar/top.tsx
import Image from 'next/image'
import iconPic from '../../public/icon.png'

export default function SideBarTop() {
  return (
    <div>
      <div
        className='flex flex-row items-center justify-center my-1 p-2 h-14 border-b border-gray-400 text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-red-400 content-center'
      >
        <Image width={32} height={32} src={iconPic} alt="PistonVideo Logo"/>
        <div className="ml-1">PistonVideo</div>
      </div>
    </div>
  );
}

// components/SideBar/Top.vue
<template>
  <div>
    <div
      class="flex flex-row items-center justify-center my-1 h-14 border-b border-gray-400 text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-red-400 content-center"
    >
      <img class="w-8 h-8 mr-1" src="/icon.png" />
      <div>PistonVideo</div>
    </div>
  </div>
</template>
