// components/VideoPlayerComponent.vue
<template>
  <vue-plyr :options="plyrOptions">
    <video controls crossorigin playsinline :data-poster="options.poster">
      <source v-for="source in options.sources" :key="source.src" :src="source.src" :type="source.type" />
    </video>
  </vue-plyr>
</template>

<script>
export default {
  props: ['video'],
  data() {
    return {
      plyrOptions: {
        ratio: '16:9',
      },
      options: {
        sources: [
          {
            type: 'video/mp4',
            src: this.video.videoUrl,
          },
        ],
        poster: this.video.thumbnailUrl,
      },
    };
  },
};
</script>

// components/video-player.tsx
import Plyr from 'plyr-react';
import 'plyr-react/dist/plyr.css';
import { Video } from './models/video';

export default function VideoPlayerComponent({ video }: { video: Video }) {
  return (
    <Plyr
      source={{
        /* https://github.com/sampotts/plyr#the-source-setter */
        type: 'video',
        title: video.title,
        sources: [
          {
            src: video.videoUrl,
            type: 'video/mp4',
            size: 720,
          },
        ],
        poster: video.thumbnailUrl,
        tracks: [
        ],
      }}
      options={
        {
          /* https://github.com/sampotts/plyr#options */
        }
      }
      {
        ...{
          /* Direct props for inner video tag (mdn.io/video) */
        }
      }
    />
  );
}
