// components/Video/ListComponent.vue
<template>
  <div v-if="rows" class="flex flex-wrap justify-between gap-2 overflow-hidden">
    <div v-for="rowVideos in rows" :key="rowVideos">
      <VideoCard v-for="video in rowVideos" :key="video.title" :video="video" />
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      rows: undefined,
      videos: undefined
    };
  },
  async fetch() {
    const response = await this.$axios.get("/api/suggestions", { params: { amount: 50 } });

    this.videos = response.data;
    const rows = [];

    let rowIndex = 0;
    for (const video in this.videos) {
      if (rows[rowIndex] === undefined) rows[rowIndex] = [];

      rows[rowIndex][rows[rowIndex].length] = this.videos[video];

      rowIndex++;

      if (rowIndex >= 7) {
        rowIndex = 0;
      }
    }

    this.rows = rows;
  }
};
</script>

// components/video/list.tsx
import VideoCard from './card';
import { Video } from '../models/video';
import axios from 'axios';
import { useState } from 'react';

export default function VideoList() {
  const [videos, setVideos] = useState<Video[]>([]);

  axios
    .get('backend/suggestions', { params: { amount: 10 } })
    .then((response) => {

      let videosTemp: Video[] = [];

      response.data.forEach((video: Video) => {
        videosTemp.push(video);
      });

      setVideos(videosTemp);
    });

  return (
    <div className="flex flex-wrap justify-between gap-2 overflow-hidden w-full">
      {videos.map((video) => {
        return <VideoCard video={video} />;
      })}
    </div>
  );
}
