// components/video/user-list.tsx
import VideoCard from './card';
import { Video } from '../models/video';

export default function VideoUserList({ videos }: { videos: Video[] }) {
  return (
    <div className="flex flex-wrap gap-2 overflow-hidden">
      {videos.map((video, index) => (
        <VideoCard key={index} video={video} />
      ))}
    </div>
  );
}

// components/Video/UserListComponent.vue
<template>
  <div class="flex flex-wrap gap-2 overflow-hidden">
    <VideoCard v-for="video in videos" :key="video.title" :video="video"></VideoCard>
  </div>
</template>

<script>
export default {
  props: ['id'],
  data() {
    return {
      videos: [],
    };
  },
  async fetch() {
    const response = await this.$axios.get('/api/uservideos', { params: { id: this.id } });

    this.videos = response.data;
  },
};
</script>
